getEmergencyNotice:
  call: http.post
  args:
    url: "[#CHATBOT_RESQL]/get-emergency-notice"
  result: res
  next: validateEmergencyNoticeExists

validateEmergencyNoticeExists:
  switch:
    - condition: "${getEmergencyNoticeResult.response.body.length > 0}"
      next: returnSuccess
  next: returnNotFound

returnSuccess:
  return: ${res.response.body}
  next: end

returnNotFound:
  return: "error: not found"
  next: end
