getEmergencyNotice:
  call: http.post
  args:
    url: "[#CHATBOT_RESQL]/get-emergency-notice"
  result: res
  next: validate_res

validate_res:
  switch:
    - condition: "${res.response.body.length > 0}"
      next: return_response
  next: return_not_found

return_response:
  return: ${res.response.body}
  next: end

return_not_found:
  return: "error: not found"
  next: end
