getWidgetConfig:
  call: http.post
  args:
    url: "[#CHATBOT_RESQL]/get-widget-config"
  result: res
  next: validate_response

validate_response:
  switch:
    - condition: "${res.response.body.length > 0}"
      next: return_result
  next: return_not_found

return_result:
  return: ${res.response.body}
  next: end

return_not_found:
  return: "error: not found"
  next: end
