name: Deploy Docker Compose

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev-test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'  # Only run for the 'feature' branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Check if directory exists on remote server and create if neccecary
        id: check-directory
        run: |
            ssh -i $HOME/.ssh/id_rsa ubuntu@${{ secrets.SERVER_IP }} 'if [ -d "/home/ubuntu/install/DEV" ]; then echo "Directory exists"; else mkdir -p /home/ubuntu/install/DEV && echo "Made directory"; fi'

      - name: Push repository to MAIN server
        run: rsync -az --exclude='.git/' -e "ssh -i $HOME/.ssh/id_rsa" $GITHUB_WORKSPACE/ ubuntu@${{ secrets.SERVER_IP }}:/home/ubuntu/install/DEV
      
